import {Drivers,Race, Results, Team, Tracks} from '@/app/lib/definitions'


function getTeamPlaceHolderData(): Team[]{
    return [
        {id: '', name: 'Mercedes', logo_url: '/teams/mercedes'},
        {id: '', name: 'Ferrari', logo_url: '/teams/ferrari'},
        {id: '', name: 'Maclaren', logo_url: '/teams/maclaren'},
        {id: '', name: 'Red Bull', logo_url: '/teams/redbull-racing'},
        {id: '', name: 'Racing Bulls', logo_url: '/teams/racing-bulls'},
        {id: '', name: 'Alpine', logo_url: '/teams/alpine'},
        {id: '', name: 'Haas', logo_url: '/teams/haas'},
        {id: '', name: 'Audi', logo_url: '/teams/audi'},
        {id: '', name: 'Williams', logo_url: '/teams/williams'},
        {id: '', name: 'Aston Martin', logo_url: '/teams/aston-martin'},
        {id: '', name: 'Cadillac', logo_url: '/teams/cadillac'},
    ] //Id will be generated by postgres but I need to retrieve all of 
}

function getDriverPlaceHolderData(teams: { name: string,id: string}[]){

    const teamMap = new NameToIdMap(teams)

    return [
  { id: '', first_name: 'Lando', last_name: 'Norris', team_id: teamMap.getId('Maclaren') , number: 1 },
  { id: '', first_name: 'Oscar', last_name: 'Piastri', team_id: teamMap.getId('Maclaren') , number: 81 },

  { id: '', first_name: 'Lewis', last_name: 'Hamilton', team_id: teamMap.getId('Ferrari') , number: 44 },
  { id: '', first_name: 'Charles', last_name: 'Leclerc', team_id: teamMap.getId('Ferrari') , number: 16 },

  { id: '', first_name: 'Max', last_name: 'Verstappen', team_id: teamMap.getId('Red Bull') ??'', number: 3 },
  { id: '', first_name: 'Isack', last_name: 'Hadjar', team_id: teamMap.getId('Red Bull') , number: 6 },

  { id: '', first_name: 'George', last_name: 'Russell', team_id: teamMap.getId('Mercedes') , number: 63 },
  { id: '', first_name: 'Kimi', last_name: 'Antonelli', team_id: teamMap.getId('Mercedes') , number: 12 },

  { id: '', first_name: 'Fernando', last_name: 'Alonso', team_id: teamMap.getId('Aston Martin') , number: 14 },
  { id: '', first_name: 'Lance', last_name: 'Stroll', team_id: teamMap.getId('Aston Martin') , number: 18 },

  { id: '', first_name: 'Alex', last_name: 'Albon', team_id: teamMap.getId('Williams') , number: 23 },
  { id: '', first_name: 'Carlos', last_name: 'Sainz', team_id: teamMap.getId('Williams') , number: 55 },

  { id: '', first_name: 'Nico', last_name: 'Hülkenberg', team_id: teamMap.getId('Audi') , number: 27 },
  { id: '', first_name: 'Gabriel', last_name: 'Bortoleto', team_id: teamMap.getId('Audi') , number: 5 },

  { id: '', first_name: 'Pierre', last_name: 'Gasly', team_id: teamMap.getId('Alpine') , number: 11 },
  { id: '', first_name: 'Franco', last_name: 'Colapinto', team_id: teamMap.getId('Alpine') , number: 43 },

  { id: '', first_name: 'Esteban', last_name: 'Ocon', team_id: teamMap.getId('Haas') , number: 31 },
  { id: '', first_name: 'Oliver', last_name: 'Bearman', team_id: teamMap.getId('Haas') , number: 87 },

  { id: '', first_name: 'Liam', last_name: 'Lawson', team_id: teamMap.getId('Racing Bulls') , number: 30 },
  { id: '', first_name: 'Arvid', last_name: 'Lindblad', team_id: teamMap.getId('Racing Bulls') , number: 41 },

  { id: '', first_name: 'Sergio', last_name: 'Pérez', team_id: teamMap.getId('Cadillac') , number: 11 },
  { id: '', first_name: 'Valtteri', last_name: 'Bottas', team_id: teamMap.getId('Cadillac') , number: 77 },
];
}

function getTracks(): Tracks[]{
    return  [
        { id: 'Albert Park Circuit', name: 'Albert Park Circuit', location: 'Melbourne, Australia', distance: 5278, track_image_url: '/tracks/albert-park-circuit' },
        { id: 'Shanghai International Circuit', name: 'Shanghai International Circuit', location: 'Shanghai, China', distance: 5451, track_image_url: '/tracks/shanghai-international-circuit' },
        { id: 'Suzuka Circuit', name: 'Suzuka Circuit', location: 'Suzuka, Japan', distance: 5807, track_image_url: '/tracks/Suzuka-Circuit' },
        { id: 'Miami International Autodrome', name: 'Miami International Autodrome', location: 'Miami, USA', distance: 5412, track_image_url: '/tracks/miami-international-autodrome' },
        { id: 'Circuit Gilles Villeneuve', name: 'Circuit Gilles Villeneuve', location: 'Montreal, Canada', distance: 4361, track_image_url: '/tracks/circuit-gilles-villeneuve' },
        { id: 'Circuit de Monaco', name: 'Circuit de Monaco', location: 'Monte Carlo, Monaco', distance: 3337, track_image_url: '/tracks/circuit-de-monaco' },
        { id: 'Circuit de Barcelona-Catalunya', name: 'Circuit de Barcelona-Catalunya', location: 'Barcelona, Spain', distance: 4657, track_image_url: '/tracks/circuit-de-barcelona-catalunya' },
        { id: 'Red Bull Ring', name: 'Red Bull Ring', location: 'Spielberg, Austria', distance: 4318, track_image_url: '/tracks/Red-Bull-Ring' },
        { id: 'Silverstone Circuit', name: 'Silverstone Circuit', location: 'Silverstone, United Kingdom', distance: 5891, track_image_url: '/tracks/silverstone-circuit' },
        { id: 'Circuit de Spa-Francorchamps', name: 'Circuit de Spa-Francorchamps', location: 'Spa, Belgium', distance: 7004, track_image_url: '/tracks/circuit-de-spa-francorchamps' },
        { id: 'Hungaroring', name: 'Hungaroring', location: 'Budapest, Hungary', distance: 4381, track_image_url: '/tracks/hungaroring' },
        { id: 'Circuit Zandvoort', name: 'Circuit Zandvoort', location: 'Zandvoort, Netherlands', distance: 4259, track_image_url: '/tracks/circuit-zandvoort' },
        { id: 'Autodromo Nazionale Monza', name: 'Autodromo Nazionale Monza', location: 'Monza, Italy', distance: 5793, track_image_url: '/tracks/autodromo-nazionale-monza' },
        { id: 'Baku City Circuit', name: 'Baku City Circuit', location: 'Baku, Azerbaijan', distance: 6003, track_image_url: '/tracks/baku-city-circuit' },
        { id: 'Marina Bay Street Circuit', name: 'Marina Bay Street Circuit', location: 'Singapore', distance: 4940, track_image_url: '/tracks/marina-bay-street-circuit' },
        { id: 'Circuit of the Americas', name: 'Circuit of the Americas', location: 'Austin, USA', distance: 5513, track_image_url: '/tracks/Circuit-of-the-americas' },
        { id: 'Autódromo Hermanos Rodríguez', name: 'Autódromo Hermanos Rodríguez', location: 'Mexico City, Mexico', distance: 4304, track_image_url: '/tracks/autodromo-Hermanos-rodriguez' },
        { id: 'Autódromo José Carlos Pace', name: 'Autódromo José Carlos Pace', location: 'São Paulo, Brazil', distance: 4309, track_image_url: '/tracks/autodromo-jose-carlos-pace' },
        { id: 'Las Vegas Strip Circuit', name: 'Las Vegas Strip Circuit', location: 'Las Vegas, USA', distance: 6201, track_image_url: '/tracks/las-vegas-strip-circuit' },
        { id: 'Losail International Circuit', name: 'Losail International Circuit', location: 'Lusail, Qatar', distance: 5380, track_image_url: '/tracks/losail-international-circuit' },
        { id: 'Yas Marina Circuit', name: 'Yas Marina Circuit', location: 'Abu Dhabi, UAE', distance: 5281, track_image_url: '/tracks/yas-marina-circuit' },
      ];
}


function getRaces(tracks: {id: string,name: string}[]): Race[]{
    const trackMap = new NameToIdMap(tracks);

  return  [
        { id: '', track_id: trackMap.getId('Albert Park Circuit'), laps: 58, race_date: '2026-03-08', race_start_time: '15:00:00' },
        { id: '', track_id: trackMap.getId('Shanghai International Circuit'), laps: 56, race_date: '2026-03-15', race_start_time: '15:00:00' },
        { id: '', track_id: trackMap.getId('Suzuka Circuit'), laps: 53, race_date: '2026-03-29', race_start_time: '14:00:00' },
        { id: '', track_id: trackMap.getId('Miami International Autodrome'), laps: 57, race_date: '2026-05-03', race_start_time: '16:00:00' },
        { id: '', track_id: trackMap.getId('Circuit Gilles Villeneuve'), laps: 70, race_date: '2026-05-24', race_start_time: '14:00:00' },
        { id: '', track_id: trackMap.getId('Circuit de Monaco'), laps: 78, race_date: '2026-06-07', race_start_time: '15:00:00' },
        { id: '', track_id: trackMap.getId('Circuit de Barcelona-Catalunya'), laps: 66, race_date: '2026-06-14', race_start_time: '15:00:00' },
        { id: '', track_id: trackMap.getId('Red Bull Ring'), laps: 71, race_date: '2026-06-28', race_start_time: '15:00:00' },
        { id: '', track_id: trackMap.getId('Silverstone Circuit'), laps: 52, race_date: '2026-07-05', race_start_time: '15:00:00' },
        { id: '', track_id: trackMap.getId('Circuit de Spa-Francorchamps'), laps: 44, race_date: '2026-07-19', race_start_time: '15:00:00' },
        { id: '', track_id: trackMap.getId('Hungaroring'), laps: 70, race_date: '2026-07-26', race_start_time: '15:00:00' },
        { id: '', track_id: trackMap.getId('Circuit Zandvoort'), laps: 72, race_date: '2026-08-23', race_start_time: '15:00:00' },
        { id: '', track_id: trackMap.getId('Autodromo Nazionale Monza'), laps: 53, race_date: '2026-09-06', race_start_time: '15:00:00' },
        { id: '', track_id: trackMap.getId('Baku City Circuit'), laps: 51, race_date: '2026-09-20', race_start_time: '15:00:00' },
        { id: '', track_id: trackMap.getId('Marina Bay Street Circuit'), laps: 62, race_date: '2026-10-04', race_start_time: '20:00:00' },
        { id: '', track_id: trackMap.getId('Circuit of the Americas'), laps: 56, race_date: '2026-10-25', race_start_time: '14:00:00' },
        { id: '', track_id: trackMap.getId('Autódromo Hermanos Rodríguez'), laps: 71, race_date: '2026-11-01', race_start_time: '14:00:00' },
        { id: '', track_id: trackMap.getId('Autódromo José Carlos Pace'), laps: 71, race_date: '2026-11-08', race_start_time: '14:00:00' },
        { id: '', track_id: trackMap.getId('Las Vegas Strip Circuit'), laps: 50, race_date: '2026-11-21', race_start_time: '22:00:00' },
        { id: '', track_id: trackMap.getId('Losail International Circuit'), laps: 57, race_date: '2026-11-29', race_start_time: '17:00:00' },
        { id: '', track_id: trackMap.getId('Yas Marina Circuit'), laps: 58, race_date: '2026-12-06', race_start_time: '13:00:00' },
      ];
}

class NameToIdMap{
    private NameToIdMap : Map<string, string>;
    
    constructor(objectToMap: {id:string, name: string}[]){
        //I am using name as the key as I don't know the id  
        this.NameToIdMap = new Map<string, string>();

        for(const {id, name} of objectToMap){
            this.NameToIdMap.set(name, id)
        }
    }

    public getId(name: string): string{
        return this.NameToIdMap.get(name) ?? '';//I am going to treat a empty string as not found
    }
}


export {getTeamPlaceHolderData, getRaces, getTracks, getDriverPlaceHolderData}