import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Image from 'next/image';
import "./globals.css";
import SideBar from "./ui/sidebar";
import Link from 'next/Link'
import Logo from "./ui/logo";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "F1 Compainion",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full min-w-full gap-2.5 flex flex-col items-center p-3.5 bg-background ">
        
          <div className="w-full flex items-start justify-between">
            <Logo/>
            {/* This is  */}
            {/* <span className="text-text">account info</span> */}
          </div>
        
      <div className="flex flex-1 gap-5 flex-row w-full pr-2.5">
        <SideBar />
        {children}
      </div>
      
    </body>
    </html >
  );
}
