import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SideBar from "./ui/navBarLinks";
import Logo from "./ui/logo";
import React from "react";
import InteractiveBode from "./ui/InteractiveBody";
import InteractiveBody from "./ui/InteractiveBody";
import Header from "./ui/Header/Header";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "F1 Compainion",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`h-full antialiased`}>
      {/* ${geistSans.variable} ${geistMono.variable} */}
      <body className="bg-background flex min-h-screen min-w-screen flex-col gap-9">
        <Header></Header>
        <div className="bg-foreground mx-5 my-2.5 mt-0 flex-1 rounded-2xl p-3 text-(--color-text)">
          {children}
        </div>
      </body>
    </html>
  );
}
