import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SideBar from "./ui/sidebar";
import Logo from "./ui/logo";
import React from "react";
import InteractiveBode from "./ui/InteractiveBody";
import InteractiveBody from "./ui/InteractiveBody";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "F1 Compainion",
  description: "Generated by create next app",
};

export default function RootLayout({ children }:  {children: React.ReactNode;}) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-screen min-w-screen bg-background ">
        
          <InteractiveBody logo={<Logo/>} sideBar={<SideBar/>}>
            {children}
          </InteractiveBody>
        
    </body>
    </html >
  );
}

